//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluebank.Core.Data.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlueBankEntities : DbContext
    {
        public BlueBankEntities()
            : base("name=BlueBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Cuentas> Tbl_Cuentas { get; set; }
        public virtual DbSet<Tbl_Personas> Tbl_Personas { get; set; }
        public virtual DbSet<Tbl_TiposTranssacciones> Tbl_TiposTranssacciones { get; set; }
        public virtual DbSet<Tbl_Transsacciones> Tbl_Transsacciones { get; set; }
    }
}
