//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluebank.Core.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Personas()
        {
            this.Tbl_Cuentas = new HashSet<Tbl_Cuentas>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> cedula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Cuentas> Tbl_Cuentas { get; set; }
    }
}
