//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluebank.Core.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Transsacciones
    {
        public int Numero { get; set; }
        public int CuentaNumero { get; set; }
        public int Tipo { get; set; }
        public double Saldo { get; set; }
    
        public virtual Tbl_Cuentas Tbl_Cuentas { get; set; }
        public virtual Tbl_TiposTranssacciones Tbl_TiposTranssacciones { get; set; }
    }
}
