//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluebank.Core.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cuentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Cuentas()
        {
            this.Tbl_Transsacciones = new HashSet<Tbl_Transsacciones>();
        }
    
        public int CuentaNumero { get; set; }
        public double Saldo { get; set; }
        public int Persona { get; set; }
    
        public virtual Tbl_Personas Tbl_Personas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Transsacciones> Tbl_Transsacciones { get; set; }
    }
}
